---

- name: ensure all users have access to the demo machine credential
  tower_role:
    config_file: ~/.tower_cli.cfg
    team: Sales Demo User
    role: use
    credential: Demo Machine Credential
    state: present

- name: create the demo admin machine credential
  tower_credential:
    config_file: ~/.tower_cli.cfg
    name: Demo Admin SSH Key
    description: SSH key used for shared demo administration.
    organization: Ansible Sales Demo
    kind: ssh
    username: admin
    ssh_key_data: /home/admin/.ssh/id_rsa
    state: present

- name: ensure all admins have access to the demo admin machine credential
  tower_role:
    config_file: ~/.tower_cli.cfg
    team: Sales Demo Admin
    role: use
    credential: Demo Admin SSH Key
    state: present
